name: Build to GCR
on: 
  push:
    branches:
      - main
      
env:
  IMAGE_NAME: python-check-ip
  PROJECT_ID: xthanos
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Copy Code
        uses: actions/checkout@v1
        
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0.3.0
        with: 
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: xthanos
          export_default_credentials: true
      
      - name: Login to Registry
        run: gcloud auth configure-docker --quiet
          
      - name: Build & Push to GCR
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          docker build -t asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:${TIMESTAMP} .
          docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:${TIMESTAMP}
